-   id: mkdocs
    name: mkdocs
    description: 'Project documentation with Markdown'
    entry: mkdocs build
    language: python
    language_version: python3
    types: [markdown]
    pass_filenames: false
